services:
  db:
    image: postgres:17.2-alpine
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  meilisearch:
    image: getmeili/meilisearch:v1.12
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
